Left_Arm_Lift:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001
Right_Arm_Lift:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001
Left_Arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001
Right_Arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001