<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931"/>
  <xacro:property name="length" value="0.395"/>
  <xacro:property name="width" value="0.37"/>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- base_footprint -->
  <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
        <material name="TransparentGreen" />
      </visual>
  </link>
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0.02" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!-- base_link -->
  <link name="base_link">
      <visual>
        <geometry>
            <mesh filename="package://wpr2_description/meshes/base.dae" scale="1 1 1"/>
        </geometry>
        <origin rpy = "0 0 0" xyz = "0.0 0.0 0.13"/>
      </visual>
      <visual>
        <geometry>
            <box size="0.02 0.32 0.2"/>
        </geometry>
        <origin rpy = "0 0 0" xyz = "-0.13 0.0 1.0"/>
        <material name="black" />
      </visual>
      <!-- 底盘碰撞体 -->
      <collision>
        <origin xyz="0.005 0 0.07" rpy="0 0 0" />
        <geometry>
          <box size="0.57 0.46 0.12"/>
        </geometry>
      </collision>
      <!-- 上舱盖 -->
      <collision>
        <origin xyz="-0.03 0 0.20" rpy="0 0 0" />
        <geometry>
          <box size="0.50 0.37 0.04"/>
        </geometry>
      </collision>
      <!-- 立柱 -->
      <collision>
        <origin xyz="-0.07 0 0.68" rpy="0 0 0" />
        <geometry>
          <box size="0.10 0.20 0.90"/>
        </geometry>
      </collision>
      <!-- 屏幕 -->
      <collision>
        <origin rpy = "0 0 0" xyz = "-0.13 0.0 1.0"/>
        <geometry>
            <box size="0.02 0.32 0.2"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="20"/>
        <inertia ixx="10" ixy="0.0" ixz="0.0" iyy="10" iyz="0.0" izz="10"/>
      </inertial>
  </link>

  <!-- mecanum wheel unit -->
  <xacro:macro name="mecanum_wheel" params="LR FB">
      <xacro:if value="${LR=='left'}">
        <xacro:property name="SignY" value="1"/>
        <xacro:property name="RollWheel" value="0"/>
      </xacro:if>
      <xacro:if value="${LR=='right'}">
        <xacro:property name="SignY" value="-1"/>
        <xacro:property name="RollWheel" value="3.1415926535897931"/>
      </xacro:if>
      <xacro:if value="${FB=='front'}">
        <xacro:property name="SignX" value="1"/>
      </xacro:if>
      <xacro:if value="${FB=='back'}">
        <xacro:property name="SignX" value="-1"/>
      </xacro:if>
      <link name="${FB}_${LR}_wheel_link">
          <visual>
              <origin xyz="0.0 0.06 0.0" rpy="1.570796327 0 0"/>
              <geometry>
                <xacro:if value="${(LR=='left' and FB=='front') or (LR=='right' and FB=='back')}">
                  <mesh filename="package://wpr2_description/meshes/mecanum_a.dae" scale="1 1 1"/>
                </xacro:if>
                <xacro:if value="${(LR=='right' and FB=='front')  or (LR=='left' and FB=='back')}">
                  <mesh filename="package://wpr2_description/meshes/mecanum_b.dae" scale="1 1 1"/>
                </xacro:if>
              </geometry>    
          </visual>
          <collision>
            <origin xyz="0 0.029 0" rpy="1.570796327 0 0" />
            <geometry>
              <cylinder length="0.058" radius="0.001"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="0.00001"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
          </inertial>
      </link>
      <joint name="${FB}_${LR}_wheel_joint" type="continuous">
          <parent link="base_link"/>
          <child link="${FB}_${LR}_wheel_link"/>
          <origin xyz="${SignX*length/2}   ${SignY*width/2}  0.029" rpy="${RollWheel} 0.0 0.0"/>
          <axis xyz="0 1 0"/>
      </joint>
      <transmission name="${FB}_${LR}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${FB}_${LR}_wheel_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>  
      <actuator name="${FB}_${LR}_motor">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- wheels -->
  <xacro:mecanum_wheel FB="front" LR="left"/>
  <xacro:mecanum_wheel FB="front" LR="right"/>
  <xacro:mecanum_wheel FB="back" LR="right"/>
  <xacro:mecanum_wheel FB="back" LR="left"/>

  <!-- foot unit -->
  <xacro:macro name="wheel_foot" params="LR FB">
      <xacro:if value="${LR=='left'}">
        <xacro:property name="SignY" value="1"/>
      </xacro:if>
      <xacro:if value="${LR=='right'}">
        <xacro:property name="SignY" value="-1"/>
      </xacro:if>
      <xacro:if value="${FB=='front'}">
        <xacro:property name="SignX" value="1"/>
      </xacro:if>
      <xacro:if value="${FB=='back'}">
        <xacro:property name="SignX" value="-1"/>
      </xacro:if>
      <link name="${FB}_${LR}_foot_link">
          <visual>
              <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
              <geometry>
                <box size="0.001 0.001 0.001"/>
              </geometry>    
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <cylinder length="0.01" radius="0.05"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="0.1"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
          </inertial>
      </link>
        <joint name="${FB}_${LR}_foot_joint" type="fixed">
          <parent link="base_link"/>
          <child link="${FB}_${LR}_foot_link"/>
          <origin xyz="${SignX*length/2}   ${SignY*width/1.5}  0.029" rpy="1.57 0.0 0.0"/>
      </joint>
  </xacro:macro>

  <xacro:wheel_foot FB="front" LR="left"/>
  <xacro:wheel_foot FB="front" LR="right"/>
  <xacro:wheel_foot FB="back" LR="right"/>
  <xacro:wheel_foot FB="back" LR="left"/>

  <!-- Lidar -->
  <link name="laser">
    <visual>
      <geometry>
        <cylinder length="0.001" radius="0.001"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>
  <joint name="laser_joint" type="fixed">
    <origin rpy="0 0 3.1415926" xyz="0 0 0.16"/>
    <parent link="base_link"/>
    <child link="laser"/>
  </joint>

  <!-- Gazebo plugin for RpLidar C1 -->
  <gazebo reference="laser">
    <sensor type="ray" name="rplidar_sensor">
      <pose>0 0 0.06 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159265</min_angle>
            <max_angle>3.14159265</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <!-- <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise> -->
      </ray>
      <plugin name="rplidar_ros_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan_raw</topicName>
        <frameName>laser</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>